# Generated by Django 6.0.6 on 2026-06-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_store_companymembership_storemembership"),
        ("shifts", "0003_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="accounts.storemembership",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="accounts.store",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="accounts.storemembership",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="accounts.store",
            ),
        ),
    ]
