# Generated by Django 6.0.6 on 2026-10-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0004_availability_membership_requirement_store_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="display_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "標準"),
                    ("blue", "青"),
                    ("green", "緑"),
                    ("orange", "オレンジ"),
                    ("purple", "紫"),
                    ("pink", "ピンク"),
                    ("gray", "グレー"),
                ],
                default="",
                max_length=8,
                verbose_name="表示色",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="note",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="メモ"
            ),
        ),
    ]
