# Generated by Django 6.0.6 on 2026-10-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_staffinvitation_alter_user_first_name_and_more"),
        ("shifts", "0005_shift_display_color_shift_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="day_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekday", "平日"),
                    ("holiday", "祝日"),
                    ("sunday", "日曜日"),
                    ("monday", "月曜日"),
                    ("tuesday", "火曜日"),
                    ("wednesday", "水曜日"),
                    ("thursday", "木曜日"),
                    ("friday", "金曜日"),
                    ("saturday", "土曜日"),
                ],
                max_length=10,
                null=True,
                verbose_name="曜日種別",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="締切"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="memo",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="メモ"
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="display_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "標準"),
                    ("blue", "青"),
                    ("green", "緑"),
                    ("red", "赤"),
                    ("orange", "オレンジ"),
                    ("purple", "紫"),
                    ("pink", "ピンク"),
                    ("gray", "グレー"),
                ],
                default="",
                max_length=8,
                verbose_name="表示色",
            ),
        ),
        migrations.CreateModel(
            name="AvailabilityChangeNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_notifications",
                        to="shifts.availability",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="shifts.requirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreOperatingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="営業開始時刻")),
                ("end_time", models.TimeField(verbose_name="営業終了時刻")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="accounts.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "店舗営業時間",
                "verbose_name_plural": "店舗営業時間",
            },
        ),
    ]
