# Generated by Django 6.0.6 on 2026-10-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0006_requirement_day_type_requirement_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeoperatinghours",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="営業終了時刻"),
        ),
        migrations.AlterField(
            model_name="storeoperatinghours",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="営業開始時刻"),
        ),
    ]
