# Generated by Django 6.0.6 on 2026-10-09 12:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_staffinvitation_alter_user_first_name_and_more"),
        ("shifts", "0007_alter_storeoperatinghours_end_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSubmissionDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("weekly", "週ごと"), ("monthly", "月ごと")],
                        default="monthly",
                        max_length=7,
                        verbose_name="締切の管理方法",
                    ),
                ),
                (
                    "weekly_deadline_weekday",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="締切曜日",
                    ),
                ),
                (
                    "monthly_deadline_day",
                    models.PositiveSmallIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="前月の締切日",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_deadline",
                        to="accounts.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "verbose_name": "シフト希望の提出締切",
                "verbose_name_plural": "シフト希望の提出締切",
            },
        ),
    ]
