# Generated by Django 6.0.6 on 2026-10-09 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def import_saved_time_slots(apps, schema_editor):
    Requirement = apps.get_model("shifts", "Requirement")
    Preset = apps.get_model("shifts", "RequirementTimePreset")
    database = schema_editor.connection.alias
    latest = {}
    for requirement in Requirement.objects.using(database).filter(
        store__isnull=False, required_staff_count__gte=1,
    ).order_by("created_at", "pk").iterator():
        if requirement.start_time >= requirement.end_time:
            continue
        key = (requirement.store_id, requirement.start_time, requirement.end_time)
        latest[key] = (requirement.required_staff_count, requirement.memo)
    Preset.objects.using(database).bulk_create([
        Preset(store_id=store_id, start_time=start, end_time=end,
               required_staff_count=count, memo=memo)
        for (store_id, start, end), (count, memo) in latest.items()
    ], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_staffinvitation_alter_user_first_name_and_more"),
        ("shifts", "0008_store_submission_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequirementTimePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="開始時刻")),
                ("end_time", models.TimeField(verbose_name="終了時刻")),
                (
                    "required_staff_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="必要人数",
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="メモ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_time_presets",
                        to="accounts.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "必要人数の保存済み時間帯",
                "verbose_name_plural": "必要人数の保存済み時間帯",
                "ordering": ["start_time", "end_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "start_time", "end_time"),
                        name="unique_store_requirement_time_preset",
                    )
                ],
            },
        ),
        migrations.RunPython(import_saved_time_slots, migrations.RunPython.noop),
    ]
